apiVersion: v1
clusters:
- cluster:
    server: http://{{virtual_ip_address}}:{{port}}
  name: local
contexts:
- context:
    cluster: local
    user: kubelet
  name: kubelet-context
current-context: kubelet-context
kind: Config
preferences: {}
users:
- name: kubelet
