apiVersion: v1
clusters:
- cluster:
    server: http://{{virtual_ip_address}}:{{port}}
  name: local
contexts:
- context:
    cluster: local
    user: kube-proxy
  name: kube-proxy-context
current-context: kube-proxy-context
kind: Config
preferences: {}
users:
- name: kube-proxy
