---
- name:  sysctl -w vm.max_map_count=262144
  shell: sysctl -w vm.max_map_count=262144
- name: copy file to  /lib/sysctl.d/
  copy: src={{role_path}}/templates/90-system.conf dest=/lib/sysctl.d/


