---
- hosts: all
  roles:
    - repo
    - common
- hosts: nodes
  roles:
    - docker.node
    - node
- hosts: masters
  roles:
    - docker
    - master
    - flannel
    - kubectlCMD
    - registry
- hosts: nfs-server
  roles:
    - nfs-server
  #  - nfs-client
- hosts: board
  roles:
    - docker
    - board
