---
- name: create dir for config files
  shell: mkdir -p /etc/nginx

- name: copy nginx image
  copy: src={{role_path}}/files/{{item}} dest=/etc/nginx
  with_items:
    - "nginx.tar"
- name: copy config file and script
  template: src={{role_path}}/templates/{{item}} dest=/etc/nginx mode=755
  with_items:
    - "nginx.conf"
    - "dockerrun.sh"
- name: run docker run script
  shell: /etc/nginx/dockerrun.sh


  
